<?php
	$title = 'Tenant Table';
	$this->headTitle($title);
?>

<div class="row">
	<h1 class="pull-left"><?php echo $this->escapeHtml($title); ?></h1>
    <a href="<?php echo $this->url('tenant/add'); ?>" 
        type="button" class="btn btn-primary pull-right">
            Add Tenant</a>
</div>

<table id="tenant-table" class="table table-striped table-bordered">
	<thead>
		<th>First</th>
		<th>Middle</th>
		<th>Last</th>
        <th>Code</th>
        <th>Action</th>
	</thead>

<?php foreach($tenants as $t){
	echo '<tr>';
	 	echo '<td>'.$this->escapeHtml($t->getFirstName()).'</td>';
	 	echo '<td>'.$this->escapeHtml($t->getMiddleInitial()).'</td>';
        echo '<td>'.$this->escapeHtml($t->getLastName()).'</td>';
        echo '<td>'.$this->escapeHtml($t->getCode()).'</td>';
	 	echo '<td>
		 		<a href="'.$this->url('tenant/edit', array('action' => 'edit', 'id' => $t->getId())).'">'.
		 			$this->escapeHtml('Edit').'</a>
	 			&nbsp;&nbsp;&nbsp;
	 			<a href="'.$this->url('tenant/delete', array('action' => 'delete', 'id' => $t->getId())).'">'.
		 			$this->escapeHtml('Delete').'</a>
			</td>';
 	echo '</tr>'; 
} ?>
</table>

<script type="text/javascript">
	$(document).ready(function(){
		$('#tenant-table').dataTable();
	});
</script>