<?php
	$title = 'User Table';
	$this->headTitle($title);
?>

<div class="row">
	<h1 class="pull-left"><?php echo $this->escapeHtml($title); ?></h1>
</div>

<table id="user-table" class="table table-striped table-bordered">
	<thead>
		<th>User</th>
        <th>Display Name</th>
		<th>Role</th>
		<th>Action</th>
	</thead>

<?php foreach($users as $u){
	echo '<tr>';
	 	echo '<td>'.$this->escapeHtml($u->email).'</td>';
        echo '<td>'.$this->escapeHtml($u->displayName).'</td>';
	 	echo '<td>'.$this->escapeHtml(implode(', ', $u->getRoleNames())).'</td>';
	 	echo '<td>
		 		<a href="'.$this->url('site-user/edit', array('action' => 'edit', 'id' => $u->getId())).'">'.
		 			$this->escapeHtml('Edit').'</a>
	 			&nbsp;&nbsp;&nbsp;
	 			<a href="'.$this->url('site-user/delete', array('action' => 'delete', 'id' => $u->getId())).'">'.
		 			$this->escapeHtml('Delete').'</a>
			</td>';
 	echo '</tr>'; 
} ?>
</table>

<script type="text/javascript">
	$(document).ready(function(){
		$('#user-table').dataTable();
	});
</script>