<?php
	$title = 'Person Table';
	$this->headTitle($title);
?>

<div class="row">
	<h1 class="pull-left"><?php echo $this->escapeHtml($title); ?></h1>
    <a href="<?php echo $this->url('person/add'); ?>" 
        type="button" class="btn btn-primary pull-right">
            Add Person</a>
</div>

<table id="person-table" class="table table-striped table-bordered">
	<thead>
		<th>First</th>
		<th>Last</th>
		<th>Birth Date</th>
        <th>Post Code</th>
        <th>Action</th>
	</thead>

<?php foreach($persons as $t){
	echo '<tr>';
	 	echo '<td>'.$this->escapeHtml($t->first_name).'</td>';
        echo '<td>'.$this->escapeHtml($t->last_name).'</td>';
        echo '<td>'.$this->escapeHtml($t->birth_date).'</td>';
        echo '<td>'.$this->escapeHtml($t->post_code).'</td>';
	 	echo '<td>
		 		<a href="'.$this->url('person/edit', array('action' => 'edit', 'id' => $t->id)).'">'.
		 			$this->escapeHtml('Edit').'</a>
	 			&nbsp;&nbsp;&nbsp;
	 			<a href="'.$this->url('person/delete', array('action' => 'delete', 'id' => $t->id)).'">'.
		 			$this->escapeHtml('Delete').'</a>
			</td>';
 	echo '</tr>'; 
} ?>
</table>

<script type="text/javascript">
	$(document).ready(function(){
		$('#person-table').dataTable();
	});
</script>