<?php
    $title = 'Financial Categories Table';
    $this->headTitle($title);
?>

<div class="row">
    <div class="col-md-12">
        <h1 class="pull-left"><?php echo $this->escapeHtml($title); ?></h1>
        <a href="<?php echo $this->url('financial/category/add'); ?>"
            type="button" class="btn btn-primary pull-right">
                Add Category</a>
    </div>
</div>

<table id="category-table" class="table table-striped table-bordered">
    <thead>
        <th>Name</th>
        <th>Description</th>
        <th>Action</th>
    </thead>

<?php foreach($categories as $c){
    echo '<tr>';
        echo '<td>'.$this->escapeHtml($c->getDisplayName()).'</td>';
        echo '<td>'.$this->escapeHtml($c->getDescription()).'</td>';
        echo '<td>
                <a href="'.$this->url('financial/category/edit', array('id' => $c->getId())).'">'.
                    $this->escapeHtml('Edit').'</a>
                &nbsp;&nbsp;&nbsp;
                <a href="'.$this->url('financial/category/delete', array('id' => $c->getId())).'">'.
                    $this->escapeHtml('Delete').'</a>
            </td>';
    echo '</tr>'; 
} ?>
</table>

<script type="text/javascript">
    $(document).ready(function(){
        $('#category-table').dataTable();
    });
</script>