<?php
    $title = 'Incomes Table';
    $this->headTitle($title);
?>

<div class="row">
    <h1 class="pull-left"><?php echo $this->escapeHtml($title); ?></h1>
    <a href="<?php echo $this->url('financial/income/add'); ?>" 
        type="button" class="btn btn-primary pull-right">
            Add Income</a>
</div>

<table id="income-table" class="table table-striped table-bordered">
    <thead>
        <th>Property</th>
        <th>Category</th>
        <th>Amount</th>
        <th>Date</th>
        <th>Description</th>
        <th>Action</th>
    </thead>

<?php foreach($incomes as $i){
    echo '<tr>';
        echo '<td>'.$this->escapeHtml($i->property->getName()).'</td>';
        echo '<td>'.$this->escapeHtml($i->category->getDisplay_name()).'</td>';
        echo '<td>'.$this->escapeHtml($i->getAmount()).'</td>';
        echo '<td>'.$this->escapeHtml($i->getDates()).'</td>';
        echo '<td>'.$this->escapeHtml($i->getDescription()).'</td>';
        echo '<td>
                <a href="'.$this->url('financial/income/edit', array('id' => $i->getId())).'">'.
                    $this->escapeHtml('Edit').'</a>
                &nbsp;&nbsp;&nbsp;
                <a href="'.$this->url('financial/income/delete', array('id' => $i->getId())).'">'.
                    $this->escapeHtml('Delete').'</a>
            </td>';
    echo '</tr>'; 
} ?>
</table>

<script type="text/javascript">
    $(document).ready(function(){
        $('#income-table').dataTable();
    });
</script>