<?php
	$title = 'Financials Summary';
	$this->headTitle($title);
	setlocale(LC_MONETARY, 'en_US');
?>

<div class="row">
	<h1 class="pull-left"><?php echo $this->escapeHtml($title); ?></h1>
	<a href="<?php echo $this->url('financial/report'); ?>" 
        type="button" class="btn btn-default pull-right">
            Financial Report</a>
</div>




<?php $properties = $totals = $bad = $by_property = $cash_flow_start = $cash_flow = array();  
    $excl_status = 3; $headquarter = 3;

foreach($incomes as $i){
    $p = $i->getProperty();
    $c = $i->getCategory();
    $pid = $p->getId();
    if(!isset($properties[$pid]))
        $properties[$pid] = $p->getName();

    $iexcl = $c->getExcl_cash_flow();
    $cdn = $c->getDisplay_name();

    // Total
	if(!isset($totals['income'][$cdn]))
		$totals['income'][$cdn] = 0;

	// By Property
	if(!isset($by_property[$pid]['income'][$cdn]))
		$by_property[$pid]['income'][$cdn] = 0;

	$totals['income'][$cdn] += $i->getTotal();
	$by_property[$pid]['income'][$cdn] += $i->getTotal();
	
	/* Cash flow average by property
		Total from 4-rent, 6-hoa, 7-repair-materials, 8-repair-labor, 10-taxes, 11-bad-debt
        12-improvement-labor, 13-improvement-materials
		Divided by total months in service
	*/
    if($p->getStatus_id() != $excl_status && !$iexcl){
		if(!isset($cash_flow_start[$pid]) || $cash_flow_start[$pid] > $i->date_filed)
			$cash_flow_start[$pid] = $i->date_filed;
		if(!isset($cash_flow[$pid])) 
			$cash_flow[$pid] = 0;
		$cash_flow[$pid] += $i->getTotal();
	}

	/* Total average cash flow
		Total from all cats except 5-purchase, 16-zestimate, 18-deposit
        Divided by total months in business
	*/
	if(!$iexcl){ // hard coded use headquarter for total
		if(!isset($cash_flow_start[$headquarter]) || $cash_flow_start[$headquarter] > $i->date_filed)
			$cash_flow_start[$headquarter] = $i->date_filed;
		if(!isset($cash_flow[$headquarter])) 
			$cash_flow[$headquarter] = 0;
		$cash_flow[$headquarter] += $i->getTotal();	
	}
}

foreach($expenses as $e){
	$p = $e->getProperty();
	$c = $e->getCategory();
	$pid = $p->getId();
    if(!isset($properties[$pid]))
        $properties[$pid] = $p->getName();
    
    $eexcl = $c->getExcl_cash_flow();
    $cdn = $c->getDisplay_name();

    // Total
	if(!isset($totals['expense'][$cdn]))
		$totals['expense'][$cdn] = 0;

	// By Property
	if(!isset($by_property[$pid]['expense'][$cdn]))
		$by_property[$pid]['expense'][$cdn] = 0;

	$totals['expense'][$cdn] -= $e->getTotal();
	$by_property[$pid]['expense'][$cdn] -= $e->getTotal();

	// Cash flow by property
    if($p->getStatus_id() != $excl_status && !$eexcl){
		if(!isset($cash_flow[$pid])) 
			$cash_flow[$pid] = 0;
		$cash_flow[$pid] -= $e->getTotal();
	}

	// Total cash flow
	if(!$eexcl)
		$cash_flow[$headquarter] -= $e->getTotal();
}

$count = 1; $now = date_create(date('Y-m-d'));
foreach($by_property as $pid => $li){
	if($pid != $headquarter){
		
		// Get cash flow
		$start = date_create($cash_flow_start[$pid]);
		$interval = date_diff($start, $now);
		$months_in_service = (int)$interval->format('%m');
		if((int)$yis = $interval->format('%y'))
			$months_in_service += ($yis*12);

		$pcf = 0;

		if($cash_flow[$pid]) 
			$pcf = number_format($cash_flow[$pid]/$months_in_service, 2); 

		$final = 0;
		if($count%2 == 1) echo '<div class="row">';
		echo '<div class="col-md-6">
			<div class="panel panel-default">
				<div class="panel-heading"><h3 class="panel-title">'.$properties[$pid].'</h3></div>
					<div class="panel-body">
						<table class="table" style="margin-bottom:0;">';
		foreach($li as $total){
			foreach($total as $cat => $amount){
                $final += $amount;
				echo '<tr>';
					echo '<td>'.$cat.'</td>';
					echo '<td>'.($amount < 0 ? '- ' : '').'$'.number_format(abs($amount), 2).'</td>';
				echo '</tr>';
			}
		} echo '<tr><td>Average Monthly Cash Flow</td><td>'.($pcf < 0 ? '- ' : '').'$'.number_format(abs($pcf), 2).'</td></tr>';
        if(isset($in[$pid])) echo '<tr><td>Average Monthly Income</td><td>'.$in[$pid]/$months_in_service.'</td></tr>';
		echo '<tr><td class="lead">Total Gain Estimate</td><td class="lead">'.($final < 0 ? '- ' : '').'$'.number_format(abs($final), 2).'</td></tr>';
		echo '</table></div></div></div>'; 
		if($count%2 == 0) echo '</div>';
		$count++;
	}
} if(($count-1)%2 !== 0){
		echo '<div class="col-md-6"></div>';
	echo '</div>';
}

// Get total cash flow
$start = date_create($cash_flow_start[3]);
$interval = date_diff($start, $now);
$months_in_service = (int)$interval->format('%m');
	if((int)$yis = $interval->format('%y'))
		$months_in_service += ($yis*12);
$tcf = 0;
if($cash_flow[$pid]) 
	$tcf = $cash_flow[3]/$months_in_service;

echo '<div class="row"><div class="col-md-12">
	<div class="panel panel-default">
		<div class="panel-heading"><h3 class="panel-title">Totals</h3></div>
			<div class="panel-body"><table class="table" style="margin-bottom:0;">';
$final = 0;
foreach($totals as $total){	
	foreach($total as $cat => $amount){
		$final += $amount;
		echo '<tr>';
			echo '<td>'.$cat.'</td>';
			echo '<td>'.($amount < 0 ? '- ' : '').'$'.number_format(abs($amount), 2).'</td>';
		echo '</tr>';
	}
}
	echo '<tr>';
		echo '<td>Average Monthly Cash Flow</td>';
		echo '<td>'.($tcf < 0 ? '- ' : '').'$'.number_format(abs($tcf), 2).'</td>';
	echo '</tr>';
	echo '<tr>';
		echo '<td class="lead">Total Gain Estimate</td>';
		echo '<td class="lead">'.($final < 0 ? '- ' : '').'$'.number_format(abs($final), 2).'</td>';
	echo '</tr>';
echo '</table></div></div></div></div>'; ?>