<?php
	$title = 'Financials Report';
	$this->headTitle($title);
	setlocale(LC_MONETARY, 'en_US');
?>

<div class="row">
    <div class="col-md-12">
	   <h1 class="pull-left"><?php echo $this->escapeHtml($title); ?></h1>
	   <a href="<?php echo $this->url('financial'); ?>" 
	        type="button" class="btn btn-default pull-right">
	            Cancel</a>
    </div>
</div>

<div class="row">
    <div class="col-sm-5">
        <?php $form->setAttribute('action', $this->url());
        $form->prepare();
        $form->get('submit')->setValue('Generate Report');

        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag(); ?>
    </div>
</div>

<?php $report = $by_property = $properties = array();
    $end = isset($to) ? $to : NULL; $start = isset($from) ? $from : NULL;

    $exclude = array(16,18); // zestimate, deposite
foreach($incomes as $i){
    $pid = $i->property->getId();
    if(!isset($properties[$pid]))
        $properties[$pid] = $i->property->getName();  
    $cid = $i->category->getId();
    $cdn = $i->category->getDisplay_name();
    // Report
    if(!in_array($cid, $exclude)){
        if(!isset($report['income'][$cdn]['total']))
            $report['income'][$cdn]['total'] = 0;
        
        // By Property
        if(!isset($by_property[$pid]['income'][$cdn]['total']))
            $by_property[$pid]['income'][$cdn]['total'] = 0;
        
        $report['income'][$cdn]['total'] += $i->getTotal($end, $start);
        $report['income'][$cdn]['itemized'][] = $i;

        $by_property[$pid]['income'][$cdn]['total'] += $i->getTotal($end, $start); 
        $by_property[$pid]['income'][$cdn]['itemized'][] = $i;
    }
}

foreach($expenses as $e){
    $pid = $e->property->getId();
    if(!isset($properties[$pid]))
        $properties[$pid] = $i->property->getName();
    $cid = $e->category->getId();
    $cdn = $e->category->getDisplay_name();

    if(!in_array($cid, $exclude)){
        // Report
        if(!isset($report['expense'][$cdn]['total']))
            $report['expense'][$cdn]['total'] = 0;
        
        // By Property
        if(!isset($by_property[$pid]['expense'][$cdn]['total']))
            $by_property[$pid]['expense'][$cdn]['total'] = 0;
        
        $report['expense'][$cdn]['total'] -= $e->getTotal($end, $start);
        $report['expense'][$cdn]['itemized'][] = $e;

        $by_property[$pid]['expense'][$cdn]['total'] -= $e->getTotal($end, $start);
        $by_property[$pid]['expense'][$cdn]['itemized'] = $e;
    }
} ?>

<?php if($report): ?>
<div class="row"> 
<div class="col-md-6">

<h2>Income:</h2>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
<?php if(!empty($report['income'])): foreach($report['income'] as $k => $i): $id = str_replace(' ', '', $k); ?>
    <div class="panel-heading" role="tab" id="heading<?php echo $id; ?>">
        <a data-toggle="collapse" data-parent="#accordion" href="#data<?php echo $id; ?>" aria-expanded="false" aria-controls="collapse<?php echo $id; ?>">
            <h4 class="panel-title">
                <?php echo $k; ?>
                <span class="pull-right">
                    <?php echo '$'.$i['total']; ?>    
                </span>
            </h4>
        </a>
    </div>
    <div id="data<?php echo $id; ?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<?php echo $id; ?>">
    <?php foreach($i['itemized'] as $i): $pid = $i->property->getId(); ?>
        <div class="panel-body">
            <?php if($i->date_from) 
                $i->amount = isset($by_property[$pid]['income'][$k]['total'])
                    ? $by_property[$pid]['income'][$k]['total'] 
                    : $i->amount;  
                echo '<p><strong>Property: </strong>'.$properties[$pid].'</p>';
                echo '<p><strong>Amount: </strong>$'.$i->amount.'</p>';
                echo '<p><strong>Description: </strong>'.$i->getDescription().'</p>';
                echo '<p><strong>Note: </strong>'.$i->note.'</p>';
            ?>
        </div>   
    <?php endforeach; ?>
    </div>
<?php endforeach; endif; ?>
</div></div>

</div><div class="col-md-6">

<h2>Expense:</h2>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
<?php if(!empty($report['expense'])): foreach($report['expense'] as $k => $i): $id = str_replace(array('&', ' '), '', $k); ?>
    <div class="panel-heading" role="tab" id="heading<?php echo $id; ?>">
        <a data-toggle="collapse" data-parent="#accordion" href="#data<?php echo $id; ?>" aria-expanded="false" aria-controls="collapse<?php echo $id; ?>">
            <h4 class="panel-title">
                <?php echo $k; ?>
                <span class="pull-right">
                    <?php echo '$'.$i['total']; ?>    
                </span>
            </h4>
        </a>
    </div>
    <div id="data<?php echo $id; ?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<?php echo $id; ?>">
    <?php foreach($i['itemized'] as $i): $pid = $i->property->getId(); ?>
        <div class="panel-body">
            <?php if($i->date_from) 
                $i->amount = isset($by_property[$pid]['expense'][$k]['total'])
                    ? $by_property[$pid]['expense'][$k]['total'] 
                    : $i->amount; 
                echo '<p><strong>Property: </strong>'.$properties[$pid].'</p>';
                echo '<p><strong>Amount: </strong>$'.abs($i->amount).'</p>';
                echo '<p><strong>Description: </strong>'.$i->getDescription().'</p>';
                echo '<p><strong>Note: </strong>'.$i->note.'</p>';
            ?>
        </div>   
    <?php endforeach; ?>
    </div>
<?php endforeach; endif; ?>
</div></div>

</div></div>

<?php endif; ?>