<?php $title = 'Add Role'; $this->headTitle($title); ?>

<div class="row">
    <h1 class="pull-left"><?php echo $this->escapeHtml($title); ?></h1>
    <a href="<?php echo $this->url('role'); ?>" 
        type="button" class="btn btn-default pull-right">
            Cancel</a>
</div>
<div class="row">
    <div class="col-sm-5">
        <?php $form->setAttribute('action', $this->url());
        $form->prepare();
        $form->get('submit')->setValue('Add Role');

        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag(); ?>
    </div>
</div>