<div class="row"><div class="col-md-12">
    <div id="tos">
        <h1>Terms of Service</h1>
        <p>Last updated: May 2, 2014</p>

        <p>
            Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the http://a-27inc.com website (the "Service") operated by A-27, Inc. ("us", "we", or "our").
            Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Service.
            By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.
        </p>

        <h4>Accounts</h4>
        <p>
            When you create an account with us, you must provide us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.
            You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password, whether your password is with our Service or a third-party service.
            You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.
        </p>    

        <h4>Cookies</h4>
        <p>
            Like most interactive web sites this Company’s website [or ISP] uses cookies to enable us to retrieve user details for each visit.
            Cookies are used in some areas of our site to enable the functionality of this area and ease of use for those people visiting.
        </p>

        <h4>Log Files</h4>
        <p>
            We use IP addresses to analyze trends, administer the site, track user movement, and gather broad demographic information for aggregate use. 
            We do not link IP addresses to personally identifiable information, and we do not distribute or share IP information with any third parties.
        </p>

        <h4>Links To Other Web Sites</h4>
        <p>
            Our Service may contain links to third-party web sites or services that are not owned or controlled by A-27, Inc..
            A-27, Inc. has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. 
            You further acknowledge and agree that A-27, Inc. shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services.
            We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit.
        </p>

        <h4>Links to this website</h4>
        <p>
            You may not create a link to any page of this website without our prior written consent. 
            If you do create a link to a page of this website you do so at your own risk and the exclusions and limitations set out above will apply to your use of this website by linking to it.
        </p>

        <h4>Termination</h4>
        <p>
            We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
            All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.
            We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
            Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service.
            All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.
        </p>

        <h4>Governing Law</h4>
        <p>
            These Terms shall be governed and construed in accordance with the laws of Florida, United States, without regard to its conflict of law provisions.
            Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. 
            If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. 
            These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.
        </p>

        <h4>Changes</h4>
        <p>
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
            By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. 
            If you do not agree to the new terms, please stop using the Service.
        </p>

        <h4>Copyright Notice</h4>
        <p>Copyright and other relevant intellectual property rights exists on all text relating to the Company’s services and the full content of this website.</p>

        <h4>Contact Us</h4>
        <p>
            This company is registered in Florida, United States Document Number P14000039657, registered office 1054 Alpug Ave, Oviedo, FL 32765.
            If you have any questions about these Terms, please contact us.
            Contact information, can be found on our Contact Us link on our website.
        </p>
    </div>
</div></div>