<?php
	$title = 'Delete Person';
	$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>
	Are you sure that you want to delete
	'<?php echo $this->escapeHtml($person->first_name); ?>'?
</p>

<?php $url = $this->url('person/delete', array(
	'action' => 'delete',
	'id'     => $person->id)); ?>

<form action="<?php echo $url; ?>" method="POST">
	<div>
	<input type="hidden" name="id" value="<?php echo (int) $person->id; ?>" />
	<input type="submit" name="del" value="Yes" />
	<input type="submit" name="del" value="No" />
	</div>
</form>