<?php
    $title = 'Delete Property';
    $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>
    Are you sure that you want to delete
    '<?php echo $this->escapeHtml($this->property->getName()); ?>' in
    '<?php echo $this->escapeHtml($this->property->getCity()); ?>'?
</p>

<form action="<?php echo $this->url('property/delete', array(), true) ?>" method="post">
    <input type="submit" name="delete_confirmation" value="yes">
    <input type="submit" name="delete_confirmation" value="no">
</form>