<?php
	$title = 'Role Table';
	$this->headTitle($title);
?>

<div class="row">
	<div class="col-md-12">
		<h1 class="pull-left"><?php echo $this->escapeHtml($title); ?></h1>
		<a href="<?php echo $this->url('permission/add'); ?>"
			type="button" class="btn btn-primary pull-right">
				Add Permission</a>
		<a href="<?php echo $this->url('role/add'); ?>"
			type="button" class="btn btn-primary pull-right" style="margin-right:30px;">
				Add Role</a>
	</div>
</div>

<table id="user-table" class="table table-striped table-bordered">
	<thead>
		<th>Role</th>
		<th>Permissions</th>
		<th>Action</th>
	</thead>

<?php foreach($roles as $r): ?>
	<tr>
	 	<td>
			<a href="<?php echo $this->url('role/view', array('action' => 'view', 'id' => $r->getId())) ?>">
				<?php echo $this->escapeHtml($r->name) ?>
			</a>
		</td>
	 	<td><?php echo $this->escapeHtml(implode(', ', $r->getPermissionNames())) ?></td>
		<?php if($r->getName() == 'guest'): ?>
		<td>System</td>
        <?php else: ?>
		<td>
			<a href="<?php echo $this->url('role/edit', array('action' => 'edit', 'id' => $r->getId())) ?>">
				Edit
			</a>
			<a href="<?php echo $this->url('role/delete', array('action' => 'delete', 'id' => $r->getId())) ?>">
				Delete
			</a>
		</td>
		<?php endif; ?>
 	</tr>
<?php endforeach; ?>
</table>

<script type="text/javascript">
	$(document).ready(function(){
		$('#user-table').dataTable();
	});
</script>