<?php
	$title = 'Role Table';
	$this->headTitle($title);
?>

<div class="row">
	<h1 class="pull-left"><?php echo $this->escapeHtml($title); ?></h1>
    <a href="<?php echo $this->url('permission/add'); ?>" 
        type="button" class="btn btn-primary pull-right">
            Add Permission</a>
    <a href="<?php echo $this->url('role/add'); ?>" 
        type="button" class="btn btn-primary pull-right" style="margin-right:30px;">
            Add Role</a>
</div>

<table id="user-table" class="table table-striped table-bordered">
	<thead>
		<th>Role</th>
		<th>Permissions</th>
		<th>Action</th>
	</thead>

<?php foreach($roles as $r){
	echo '<tr>';
	 	echo '<td>'.$this->escapeHtml($r->name).'</td>';
	 	echo '<td>'.$this->escapeHtml(implode(', ', $r->getPermissionNames())).'</td>';
	 	if($r->getName() == 'guest') 
            echo '<td>System</td>';
        else echo '<td>
		 		<a href="'.$this->url('role/edit', array('action' => 'edit', 'id' => $r->getId())).'">'.
		 			$this->escapeHtml('Edit').'</a>
	 			&nbsp;&nbsp;&nbsp;
	 			<a href="'.$this->url('role/delete', array('action' => 'delete', 'id' => $r->getId())).'">'.
		 			$this->escapeHtml('Delete').'</a>
			</td>';
 	echo '</tr>'; 
} ?>
</table>

<script type="text/javascript">
	$(document).ready(function(){
		$('#user-table').dataTable();
	});
</script>