<?php
	$title = 'Delete Expense';
	$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>
	Are you sure that you want to delete
	'<?php echo $this->escapeHtml(($expense->getDescription() ? $expense->getDescription() : 'expense').' for '.$expense->getAmount()); ?>'?
</p>

<?php $url = $this->url('financial/expense/delete', array(
	'action' => 'delete',
	'id'     => $expense->getId())); ?>

<form action="<?php echo $url; ?>" method="POST">
	<div>
	<input type="hidden" name="id" value="<?php echo (int) $expense->getId(); ?>" />
	<input type="submit" name="del" value="Yes" />
	<input type="submit" name="del" value="No" />
	</div>
</form>