<?php $title = 'Add Expense'; $this->headTitle($title); ?>

<div class="row">
    <div class="col-md-12">
        <h1 class="pull-left"><?php echo $this->escapeHtml($title); ?></h1>
        <a href="<?php echo $this->url('financial/expense'); ?>"
            type="button" class="btn btn-default pull-right">
                Cancel</a>
    </div>
</div>
<div class="row">
    <div class="col-sm-5">
        <?php $form->setAttribute('action', $this->url());
        $form->prepare();
        $form->get('submit')->setValue('Add Expense');

        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag(); ?>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('input[name="expensefieldset[dateFiled]"]').on('change', function() {
            var year = $(this).val().substring(0,4);
            if (year > 0) {
                $('select[name="expensefieldset[taxYear]"]').val(year);
            }
        });
    });
</script>