<div class="row">
    <div class="jumbotron">
        <h1><?php echo $this->translate('A-27, Inc. - Property Experts'); ?></h1>
        <h3><?php echo $this->translate('Close the Foreclosed, Renovate the Ugly, & Provide Clean Rental Properties.'); ?></h3>
    </div>
</dic>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title lead"><?php echo $this->translate('For Rent'); ?></h2>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Above the ordinary rentals: View available units in Wekiva Springs and Altamonte Springs.'); ?></p>
                <a class="btn btn-success pull-right" href="<?php echo $this->url('rent'); ?>">
                    <?php echo $this->translate('View Properties'); ?></a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title lead"><?php echo $this->translate('For Sale') ?></h2>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Move-in ready fast closing: View homes for sale in Seminole county.'); ?></p>
                <a class="btn btn-success pull-right" href="<?php echo $this->url('sell'); ?>">
                    <?php echo $this->translate('View Properties'); ?></a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title lead"><?php echo $this->translate('Investors'); ?></h2>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('View company financials, chose to invest, and start accumulating dividends.'); ?></p>
                <a class="btn btn-success pull-right" href="<?php echo $this->url('zfcuser/register'); ?>">
                    <?php echo $this->translate('Register Now'); ?></a>
            </div>
        </div>
    </div>
</div>