<?php
	$title = 'Allocation Table';
	$this->headTitle($title);
?>

<div class="row">
	<h1 class="pull-left"><?php echo $this->escapeHtml($title); ?></h1>
    <a href="<?php echo $this->url('investor/allocation/add'); ?>" 
        type="button" class="btn btn-primary pull-right">
            Add Allocation</a>
</div>

<table id="user-table" class="table table-striped table-bordered">
	<thead>
        <th>Investor</th>
        <th>Category</th>
        <th>Property</th>
		<th>Allocation</th>
		<th>Action</th>
	</thead>

<?php foreach($allocations as $a){
    //var_dump($a->getProperty()); die;
	echo '<tr>';
	 	echo '<td>'.$this->escapeHtml($a->getUser()->getDisplayName()).'</td>';
	 	echo '<td>'.$this->escapeHtml($a->getCategory()->getDisplayName()).'</td>';
        echo '<td>'.$this->escapeHtml($a->getProperty()->getName()).'</td>';
        echo '<td>'.$this->escapeHtml($a->getAllocation()).'</td>';
        echo '<td>
		 		<a href="'.$this->url('investor/allocation/edit', array('action' => 'edit', 'id' => $a->getId())).'">'.
		 			$this->escapeHtml('Edit').'</a>
	 			&nbsp;&nbsp;&nbsp;
	 			<a href="'.$this->url('investor/allocation/delete', array('action' => 'delete', 'id' => $a->getId())).'">'.
		 			$this->escapeHtml('Delete').'</a>
			</td>';
 	echo '</tr>'; 
} ?>
</table>

<script type="text/javascript">
	$(document).ready(function(){
		$('#user-table').dataTable();
	});
</script>