<?php
    $name = $name ? $name : $email;
	$title = 'Investment for '.$name;
	$this->headTitle($title);
?>

<div class="row">
	<h1 class="pull-left"><?php echo $this->escapeHtml($title); ?></h1>
</div>

<table id="user-table" class="table table-striped table-bordered">
	<thead>
        <th></th>
        <th>Property</th>
        <th>Investment Type</th>
        <th>Allocation</th>
		<th>Eligible Dividend (YTD)</th>
        <th>Estimated Cash-Out Value</th>
	</thead>

<?php $value_total = $value_in_total = $co_value_total = 0; $definitions = array(); 
foreach($allocations as $a){
    $in = $a->getCategory()->getSymbol() == '$';
    $is_ass = $a->getCategory()->getName() == 'assessment';
    $pid = $a->getProperty()->getId();
    $definitions[$a->getCategory()->getDisplayName()] = $a->getCategory()->getDescription();
    if($a->getCategory()->getNote())
    	$definitions[$a->getCategory()->getDisplayName()] .= '<br/>'.$a->getCategory()->getNote();
    
    switch(true){
    	case $in:
	    $co_value = $value = $a->getAllocation();
	    $value_in_total += $value;
	    break;
	
	case $is_ass:
	    $value = $summary->getYtd_assessment()
	        ? $summary->getYtd_assessment() * ($a->getAllocation() / 100) : 0;
	    $co_value = $summary->getProperty_assessment_total() 
	    	? $summary->getProperty_assessment_total() * ($a->getAllocation() / 100) : 0; 
	    break;
	
    case $a->getCategory()->getName() == 'stock-asset':
        $value = 'Not Available';
        $co_value = $summary->getProperty_total($pid) 
            ? $summary->getProperty_total($pid) * ($a->getAllocation() / 100) : 'Not Set';
        break;

	default:
	    $value = $summary->getYtd_property_profit($pid) 
	        ? $summary->getYtd_property_profit($pid) * ($a->getAllocation() / 100) : 'Not Set';
	    $co_value = $summary->getProperty_total($pid) 
	    	? $summary->getProperty_total($pid) * ($a->getAllocation() / 100) : 'Not Set';	
    }
    
    if(!$in && is_numeric($value)){
        $value_total += $value;
	$value = ($value < 0 ? '-' : '') . '$'.number_format(abs($value), 2, '.', ',');   
    } elseif($in && is_numeric($value)){
        $value = '$'.number_format($value, 2, '.', ',');   
    } if(is_numeric($co_value)){
        $co_value_total += $co_value;
        $co_value = ($co_value < 0 ? '-' : '') . '$'.number_format(abs($co_value), 2, '.', ',');    
    }

	echo '<tr>';
        echo '<td></td>';
	 	echo '<td>'.$this->escapeHtml($a->getProperty()->getName()).'</td>';
        echo '<td>'.$this->escapeHtml($a->getCategory()->getDisplayName()).'</td>';
        echo '<td>'.$this->escapeHtml($a->getCategory()->getSymbol().number_format($a->getAllocation(), 2, '.', ',')).'</td>';
        echo '<td>'.($in ? '' : $value).'</td>';
        echo '<td>'.$co_value.'</td>';
 	echo '</tr>'; 
} if($value_total || $co_value_total): ?>
    <tr>
        <td><strong>Total:</strong></td>
        <td></td><td></td>
        <td><strong>$<?php echo number_format($value_in_total, 2, '.', ','); ?></strong></td>
        <td><strong>$<?php echo number_format($value_total, 2, '.', ','); ?></strong></td>
        <td><strong>$<?php echo number_format($co_value_total, 2, '.', ','); ?></strong></td>
    </tr>
<?php endif; ?>
</table>

<h2>Definitions</h2>
<?php foreach($definitions as $title => $description): ?>
	<p><strong><?php echo $title; ?>:</strong> <?php echo $description; ?></p>
<?php endforeach; ?>

<script type="text/javascript">
	$(document).ready(function(){
		$('#user-table').dataTable({'order':[]});
	});
</script>