<div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
<h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3>
<a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>
<div style="clear:both;"></div>
<?php if(!$this->hasRole(array('super_admin', 'admin', 'investor', 'landlord', 'demo'))): ?>
	<p class="lead text-danger">NO ACCESS GRANTED: To complete your registration, please call Alex @ 321-348-4864</p>
<?php endif; ?>